[features]
seeds = false
skip-lint = false

[programs.localnet]
multisig = "8XHSyugWk2uYagCREiD2fSRkgGcTPYvwipXgd9c7em2i"

[programs.devnet]
multisig = "8XHSyugWk2uYagCREiD2fSRkgGcTPYvwipXgd9c7em2i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/rajfta/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
